from enum import Enum

class Classifier(str, Enum):
    KNEIGHBORS_CLASSIFIER = "KNEIGHBORS_CLASSIFIER"
    MLP_CLASSIFIER = "MLP_CLASSIFIER"
    RANDOM_FOREST_CLASSIFIER = "RANDOM_FOREST_CLASSIFIER"
    SVC_CLASSIFIER = "SVC_CLASSIFIER"