from enum import Enum

class TrainingState(str, Enum):
    NO_ACTIVE_TRAINING = "NO_ACTIVE_TRAINING",
    FEATURE_EXTRACTION = "FEATURE_EXTRACTION",
    MODEL_FITTING = "MODEL_FITTING",
    MODEL_TRAINING = "MODEL_TRAINING",
    CLASSIFICATION_REPORT = "CLASSIFICATION_REPORT"
    # TODO add error states
    