from enum import Enum

class Normalization(str, Enum):
    MIN_MAX_SCALER = "MIN_MAX_SCALER"
    NORMALIZER = "NORMALIZER"
    QUANTILE_TRANSFORMER = "QUANTILE_TRANSFORMER"
    ROBUST_SCALER = "ROBUST_SCALER"
    STANDARD_SCALER = "STANDARD_SCALER"