from enum import Enum

Imputation = Enum("Imputation", """
MEAN_IMPUTATION
ZERO_INTERPOLATION
LINEAR_INTERPOLATION
QUADRATIC_INTERPOLATION
CUBIC_INTERPOLATION
MOVING_AVERAGE_IMPUTATION
LAST_OBSERVATION_CARRIED_FORWARD_IMPUTATION
""")

Normalization = Enum("Normalizer", """
MIN_MAX_SCALER
NORMALIZER
QUANTILE_TRANSFORMER
ROBUST_SCALER
STANDARD_SCALER
""")

Classifier = Enum("Classifier", """
MLP_CLASSIFIER
SV_CLASSIFIER
RANDOM_FOREST_CLASSIFIER
KNEIGHBORS_CLASSIFIER
""")

Feature = Enum("Feature", """
MIN
MAX
VARIANCE
ENERGY
AUTOREGRESSIVE_CORRELATION
MEAN
IQR
PEARSON_CORRELATION
SKEWNESS
KURTOSIS
FOURIER_TRANSFORM
""")


