from enum import Enum

class Imputation(str, Enum):
    MEAN_IMPUTATION = "MEAN_IMPUTATION"
    ZERO_INTERPOLATION = "ZERO_INTERPOLATION"
    LINEAR_INTERPOLATION = "LINEAR_INTERPOLATION"
    QUADRATIC_INTERPOLATION = "QUADRATIC_INTERPOLATION"
    CUBIC_INTERPOLATION = "CUBIC_INTERPOLATION"
    MOVING_AVERAGE_IMPUTATION = "MOVING_AVERAGE_IMPUTATION"
    LAST_OBSERVATION_CARRIED_FORWARD_IMPUTATION = "LAST_OBSERVATION_CARRIED_FORWARD_IMPUTATION"

class Normalizer(str, Enum):
    MIN_MAX_SCALERMIN_MAX_SCALER = "MIN_MAX_SCALERMIN_MAX_SCALER"
    NORMALIZER = "NORMALIZER"
    QUANTILE_TRANSFORMER= "QUANTILE_TRANSFORMER"
    ROBUST_SCALER = "ROBUST_SCALER"
    STANDARD_SCALER = "STANDARD_SCALER"

class Classifier(str, Enum):
    MLP_CLASSIFIER = "MLP_CLASSIFIER"
    SV_CLASSIFIER = "SV_CLASSIFIER"
    RANDOM_FOREST_CLASSIFIER = "SV_CLASSIFIER"
    KNEIGHBORS_CLASSIFIER = "KNEIGHBORS_CLASSIFIER"

class Feature(str, Enum):
    MIN = "MIN"
    MAX = "MAX"
    VARIANCE = "VARIANCE"
    ENERGY = "ENERGY"
    AUTOREGRESSIVE_CORRELATION = "AUTOREGRESSIVE_CORRELATION"
    MEAN = "MEAN"
    IQR = "IQR"
    PEARSON_CORRELATION = "PEARSON_CORRELATION"
    SKEWNESS = "SKEWNESS"
    KURTOSIS = "KURTOSIS"
    FOURIER_TRANSFORM = "FOURIER_TRANSFORM"
