from enum import Enum

#TODO lowercase all ???
class Imputation(str, Enum):
    MEAN_IMPUTATION = "MEAN_IMPUTATION"
    ZERO_INTERPOLATION = "ZERO_INTERPOLATION"
    LINEAR_INTERPOLATION = "LINEAR_INTERPOLATION"
    QUADRATIC_INTERPOLATION = "QUADRATIC_INTERPOLATION"
    CUBIC_INTERPOLATION = "CUBIC_INTERPOLATION"
    MOVING_AVERAGE_IMPUTATION = "MOVING_AVERAGE_IMPUTATION"
    LAST_OBSERVATION_CARRIED_FORWARD_IMPUTATION = "LAST_OBSERVATION_CARRIED_FORWARD_IMPUTATION"


class Normalization(str, Enum):
    MIN_MAX_SCALER = "MIN_MAX_SCALER"
    NORMALIZER = "NORMALIZER"
    QUANTILE_TRANSFORMER = "QUANTILE_TRANSFORMER"
    ROBUST_SCALER = "ROBUST_SCALER"
    STANDARD_SCALER = "STANDARD_SCALER"

# TODO write FEATUREs by the tsfresh names
class Feature(str, Enum):
    MINIMUM = "MINIMUM"
    MAXIMUM = "MAXIMUM"
    VARIANCE = "VARIANCE"
    ABS_ENERGY = "ABS_ENERGY"
    AUTOREGRESSIVE_CORRELATION = "AUTOREGRESSIVE_CORRELATION"
    MEAN = "MEAN"
    IQR = "IQR"
    PEARSON_CORRELATION = "PEARSON_CORRELATION"
    SKEWNESS = "SKEWNESS"
    KURTOSIS = "KURTOSIS"
    FOURIER_TRANSFORM = "FOURIER_TRANSFORM"


class Classifier(str, Enum):
    KNEIGHBORS_CLASSIFIER = "KNEIGHBORS_CLASSIFIER"
    MLP_CLASSIFIER = "MLP_CLASSIFIER"
    RANDOM_FOREST_CLASSIFIER = "RANDOM_FOREST_CLASSIFIER"
    SVC_CLASSIFIER = "SVC_CLASSIFIER"
